# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: None

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/freebsd-qt6.yml
